version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_saas
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 20

  flask_app:
    build:
      context: ./Flask
      dockerfile: Dockerfile
    container_name: flask-backend
    restart: always
    env_file:
      - ./Flask/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
