# Use Python base image
FROM python:3.11.4

# Set working directory
WORKDIR /app

# Copy files and install dependencies
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

# Start Flask app
CMD ["flask", "run", "--host=0.0.0.0"]